@echo off
title LoselconIZ.exe - Warning
cls
echo Run Malware?
pause
title LoselconIZ.exe - LAST WARNING!!
cls
echo ARE YOU SURE?? CLOSE IT AND DELETE IT NOW OR YOU WANT TO RUN!!
pause
Start Boom.exe
Start Plolaris2.exe
Timeout 15
Taskkill /f /im Plolaris2.exe
Taskkill /f /im Boom.exe
Start 115.exe
Start Tun.exe
Timeout 15
Taskkill /f /im 115.exe
Taskkill /f /im Tun.exe
Start Plolaris.exe
Start Tun.exe
Start 115.exe
Timeout 15
Taskkill /f /im Tun.exe
Taskkill /f /im Plolaris.exe
Taskkill /f /im 115.exe
Start Tun.exe
Start Boom.exe
Start 115.exe
Start Plolaris.exe
Start Plolaris2.exe
Timeout 15
Taskkill /f /im Tun.exe
Taskkill /f /im Plolaris.exe
Taskkill /f /im 115.exe
Taskkill /f /im Boom.exe
Taskkill /f /im Plolaris2.exe